services:
  php:
    image: php:8.0-apache
    container_name: php
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./php/www:/var/www/html
      - uploads_data:/var/www/html/uploads
    command: sh -c "chown -R www-data:www-data /var/www/html/uploads && chmod -R 775 /var/www/html/uploads && apache2-foreground"
    networks:
      - app-network
  db:
    image: mysql:8.4
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file:
      - database/.env
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:
  uploads_data:

networks:
  app-network:
    driver: bridge